### ISSUE TITLE
Realizar testes com usuários para validar fluxo do app

### ISSUE THREAD

**Issue by fabmont** [fabmont/pi-desenvolvimento-mobile-iesb#5]
Testar é fundamental e nesta etapa vai ajudar bastante para termos certeza que nosso app está coerente e fácil de usar.

Dito isso, testaremos os protótipos feitos com amigos e familiares e levantar possíveis dúvidas que eles tiverem e com isso ajustar o que for necessário.

**Comment by JuliaDaphny** [comment]
Aaaa também acho que devemos colocar a receita do "churrasco rustico" no feed pois lá não tem, porque quando clicamos em qualquer receita do feed é redirecionando para os "detalhes" e "receita" desse churrasco!

**Comment by JoaoVictor061** [comment]
Alguns feedback que recebi de algumas pessoas, dizia que está muito bom o protótipo, na parte da receita e o modo de preparo, talvez sentiria necessidade de colocar um vídeo mostrando a pessoa fazendo a receita, mesmo já tendo o modo de preparo e o passo, que seria interessante, ou um link para o vídeo preparando a receita...

**Comment by JoaoVictor061** [comment]
Também, dentro da receita, tem algumas coisas recomendações a fazer junto com "X" receita, para complementar ela...
Os outros feedback disse que estava muito bom, que do jeito que estava, já estava muito bom e completo e bem organizado as coisas.

**Comment by judsonmillerd** [comment]
> Alguns feedback que recebi de algumas pessoas, dizia que está muito bom o protótipo, na parte da receita e o modo de preparo, talvez sentiria necessidade de colocar um vídeo mostrando a pessoa fazendo uma receita, mesmo já tendo o modo de preparo e o passo, que seria interessante, ou um link para o vídeo preparando uma receita ..

Joao, também recebi esse feedback de colocar alguma  outra opção como: link ou até mesmo o vídeo simples do youtube ensinado como se fazer a receita, pq ficaria mais interativo e pratico para o usuário. Contudo, disseram-me que esta muito legal o protótipo.

**Comment by fabmont** [comment]
A ideia de vídeo no modo de preparo realmente é bem interessante, porém para a primeira versão não é necessária.
É algo que poderia agregar valor ao que teremos. Sem falar que traria mais desafio para o time em pouco tempo.

**Comment by fabmont** [comment]
> Está legalzinho o protótipo mais achei estranho o fato de que quando estamos na tela do feed não conseguimos acessar os favoritos, está certo isso?

O usuário poderá clicar na barra de navegação inferior para acessar as receitas favoritadas... com isso a gente não precisa colocar outro gatilho pra essa tela na tela de feed. Ao meu ver.
![image](https://user-images.githubusercontent.com/43193827/134060345-1f254e6f-ed23-4b9c-90c1-d739a7e1f7bc.png)

**Comment by fabmont** [comment]
> Aaaa também acho que devemos colocar a receita do "churrasco rustico" no feed pois lá não tem, porque quando clicamos em qualquer receita do feed é redirecionando para os "detalhes" e "receita" desse churrasco!

Show! Vamos ajustar isso pra que tenhamos uma continuidade legal na navegação do protótipo. 👌🏼

**Comment by JuliaDaphny** [comment]
> > Está legalzinho o protótipo mais achei estranho o fato de que quando estamos na tela do feed não conseguimos acessar os favoritos, está certo isso?
> 
> O usuário poderá clicar na barra de navegação inferior para acessar as receitas favoritadas... com isso a gente não precisa colocar outro gatilho pra essa tela na tela de feed. Ao meu ver.
> ![image](https://user-images.githubusercontent.com/43193827/134060345-1f254e6f-ed23-4b9c-90c1-d739a7e1f7bc.png)

Então Fabricio esse botão de "favorito" que esta no feed não funciona, não estou dizendo pra colocar outro botão ou coisa parecida. Estou dizendo que quando clicamos no botão "favorito" estando no feed não é redirecionado para a tela de "Favoritos".

**Comment by JuliaDaphny** [comment]
> Alguns feedback que recebi de algumas pessoas, dizia que está muito bom o protótipo, na parte da receita e o modo de preparo, talvez sentiria necessidade de colocar um vídeo mostrando a pessoa fazendo a receita, mesmo já tendo o modo de preparo e o passo, que seria interessante, ou um link para o vídeo preparando a receita...

Concordo João, seria legal ter vídeos.

**Comment by maysvx** [comment]
Recebi um feedback positivo de duas pessoas, relataram um visual agradável aos olhos e facilidade para navegar pelo App, único ponto negativo que me relataram foi da semelhança entre a pagina do feed e pagina de favoritos, segundo os usuários este problema deixou um pouco difícil  diferenciar em qual das duas paginas estariam, exceto esse comentário todos os outros que recebi foram positivos.

![image](https://user-images.githubusercontent.com/72236606/134091568-6574afe2-d186-4bc9-9cbc-a76038ec94e0.png)
![image](https://user-images.githubusercontent.com/72236606/134091609-ab05339a-9e27-46df-afad-62fce24cc345.png)

**Comment by hackerxxx1** [comment]
A maioria dos feedbacks foram todos positivos no geral, só foi pontuado alguns detalhes. O pessoal achou que deveria ter mais vizualizaçoes de receitas, os botões nao fucionam as vezes dependendo da flow, mas funcionam na flow certa e esses foram os feedbacks

**Comment by CaioodosSantos** [comment]
Os feedbacks que recebi foram muitos bons em relação as telas, porém percebi que na tela de "Preparar receita" tem um erro de escrita, está receira, também recebi algumas reclamações de um amigo com problema de visão que (as letras estão um pouco apagadas em blocos de digitação) e (o tempo de preparo e dificuldade também estarem apagados pela cor fraca), assim tornando nosso app não tão acessível.

**Comment by CaioodosSantos** [comment]
recebi de feedback também, sobre a página de "editar receita", pessoal comentou sobre os campos (salada e salada vegana) estarem meio soltos, ai tem a dificuldade de saber se ele é campo de digitar ou não, seria legal colocar dentro de uma box colorida talvez.
![image](https://user-images.githubusercontent.com/64568292/134267051-800e8df8-1ece-41e6-9f4d-fc1a5080c128.png)
